# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockscreener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='signals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Close', models.FloatField()),
                ('ewma_10', models.FloatField()),
                ('ewma_20', models.FloatField()),
                ('ewma_50', models.FloatField()),
                ('ewma_100', models.FloatField()),
                ('var', models.FloatField()),
                ('mean', models.FloatField()),
                ('cv', models.FloatField()),
                ('BBG', models.CharField(max_length=12)),
                ('lastUpdate', models.DateTimeField()),
            ],
        ),
    ]
