# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-16 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockscreener', '0003_auto_20170316_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='batch_run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BBG', models.CharField(max_length=12)),
                ('CDR', models.CharField(max_length=12)),
                ('web_source', models.CharField(max_length=12)),
                ('IDX', models.CharField(max_length=12)),
                ('isWorking', models.BooleanField()),
                ('mnemo', models.CharField(max_length=12)),
            ],
        ),
    ]
